<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PlateLens.Domain/PlateLens.Domain.csproj" />
    <ProjectReference Include="../PlateLens.Infra.Data/PlateLens.Infra.Data.csproj" />
  </ItemGroup>
</Project>
